"""
LLM Council — Redesigned for Novel Finding generation.
Council question changed from "interpret simulation" to
"what NEW thing have we discovered that no paper said?"

Council composition (NVIDIA NIM):
  Agent 1 — Dr. Statistician       → openai/gpt-oss-20b
  Agent 2 — Dr. Epidemiologist     → meta/llama-3.2-3b-instruct
  Agent 3 — Dr. Analyst/Critic     → nvidia/nemotron-3-nano-omni-30b-a3b-reasoning
  Chair   — Consensus Synthesiser  → openai/gpt-oss-120b (master)
"""
import json
import re
from openai import OpenAI

NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"

COUNCIL_MODELS = {
    "gpt_20b": {
        "model": "openai/gpt-oss-20b",
        "temperature": 1.0, "top_p": 1.0, "max_tokens": 4096,
        "extra_body": None, "has_reasoning": True,
    },
    "llama_3b": {
        "model": "meta/llama-3.2-3b-instruct",
        "temperature": 0.2, "top_p": 0.7, "max_tokens": 1024,
        "extra_body": None, "has_reasoning": False,
    },
    "nemotron": {
        "model": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
        "temperature": 0.6, "top_p": 0.95, "max_tokens": 8192,
        "extra_body": {
            "chat_template_kwargs": {"enable_thinking": True},
            "reasoning_budget": 4096,
        },
        "has_reasoning": True,
    },
    "gpt_120b": {
        "model": "openai/gpt-oss-120b",
        "temperature": 1.0, "top_p": 1.0, "max_tokens": 4096,
        "extra_body": None, "has_reasoning": True,
    },
}

MODEL_SELECTION_AGENTS = [
    {
        "name": "Dr. Statistician", "role": "Biostatistician", "model_key": "gpt_20b",
        "lens": (
            "You are a biostatistician. Assess which computational model(s) best fit "
            "the available parameters. Consider data types, CI coverage, and completeness. "
            "Be specific — name the model and justify with data evidence."
        ),
    },
    {
        "name": "Dr. Epidemiologist", "role": "Clinical Epidemiologist", "model_key": "llama_3b",
        "lens": (
            "You are a clinical epidemiologist. Assess population heterogeneity, "
            "study design compatibility, and whether parameters come from comparable populations. "
            "Flag mismatches that affect model validity."
        ),
    },
    {
        "name": "Dr. Analyst", "role": "Computational Research Analyst", "model_key": "nemotron",
        "lens": (
            "You are a computational analyst. Assess practical executability of each model. "
            "Which algorithms will the available data actually support? "
            "Recommend running MULTIPLE models if data allows — more algorithms = richer insight."
        ),
    },
]

INSIGHT_SYNTHESIS_AGENTS = [
    {
        "name": "Dr. Clinician", "role": "Clinical Practitioner", "model_key": "gpt_20b",
        "lens": (
            "You are a senior clinician. You have seen simulation results AND novel hypotheses "
            "generated by combining multiple papers. Your job: identify the single most clinically "
            "important NEW finding — something no individual paper said, that changes how "
            "a clinician should think about this condition. Be specific. Name exact numbers."
        ),
    },
    {
        "name": "Dr. Researcher", "role": "Research Scientist", "model_key": "llama_3b",
        "lens": (
            "You are a research scientist. You have simulation outputs and cross-paper hypotheses. "
            "Identify what is GENUINELY NEW from a research perspective — not a restatement "
            "of existing knowledge but an emergent finding from combining these papers. "
            "What study should be funded next, and why specifically?"
        ),
    },
    {
        "name": "Dr. Critic", "role": "Methodological Critic", "model_key": "nemotron",
        "lens": (
            "You are a rigorous methodological critic. Challenge the novel hypotheses and "
            "simulation findings. What assumptions could be wrong? Where is the evidence "
            "weakest? What would change the conclusion? Be harsh but constructive — "
            "stakeholders need to know what they can defend and what they cannot."
        ),
    },
]

CONSENSUS_PROMPT = """You are the Council Chair. Three specialists have debated.
Synthesise into a consensus.

Return ONLY JSON:
{
  "consensus": "clear summary of agreed recommendation",
  "key_points": ["3-5 points the council agrees on"],
  "disagreements": ["points where agents differed, and how resolved"],
  "confidence": "high|medium|low",
  "caveats": ["important limitations"]
}"""

MODEL_COUNCIL_FINAL_PROMPT = """Based on the council debate, produce the final model selection.

Return ONLY JSON:
{
  "selected_model": "monte_carlo|markov_chain|bayesian_network|survival_model|hybrid_monte_carlo_markov",
  "rationale": "2-3 sentence justification",
  "scenarios": ["Base Case", "Optimistic", "Conservative"],
  "population_notes": "any weighting needed",
  "key_parameters_to_use": ["parameter names"],
  "parameters_to_flag": ["problematic parameters"],
  "confidence": "high|medium|low",
  "alternative_if_insufficient": "fallback model"
}"""

INSIGHT_COUNCIL_FINAL_PROMPT = """The council has reviewed simulation results AND novel hypotheses
from cross-paper analysis. Produce the definitive finding report.

The output MUST contain at least one NEW FINDING — something that emerges from combining
these papers that no single paper stated. Do not produce vague statements.
Be specific: name interventions, populations, outcomes, and estimated effect sizes.

Return ONLY JSON:
{
  "novel_finding": {
    "title": "Short specific title of the new finding",
    "claim": "Precise statement: [Intervention] in [Population] will [Outcome] by [estimate] vs [comparator]",
    "what_makes_it_new": "Specifically what no individual paper said",
    "evidence_chain": ["Paper X finding A supports this because...", "Paper Y finding B shows..."],
    "mechanism": "Biological/clinical mechanism making this plausible",
    "validation_study": "Specific study design: RCT|cohort, N~X, primary endpoint Y",
    "clinical_opportunity": "How this changes clinical practice",
    "commercial_opportunity": "Product, service, or patent potential",
    "confidence": "high|medium|low",
    "confidence_reasoning": "why this confidence level"
  },
  "clinical_insights": ["3-4 specific actionable insights for clinicians"],
  "research_insights": ["3-4 specific research directions with justification"],
  "simulation_interpretation": "What the multi-algorithm simulation reveals about uncertainty",
  "key_uncertainties": ["2-3 areas where evidence is weakest"],
  "actionable_next_steps": ["2-4 specific things to do: fund study X, apply for grant Y, etc."],
  "limitations": ["2-4 honest methodological limitations"],
  "overall_confidence": "high|medium|low"
}"""


def _call_model(api_key: str, model_key: str, system: str, user: str) -> str:
    cfg    = COUNCIL_MODELS[model_key]
    client = OpenAI(base_url=NVIDIA_BASE_URL, api_key=api_key)
    kwargs = dict(
        model=cfg["model"],
        messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
        temperature=cfg["temperature"],
        top_p=cfg["top_p"],
        max_tokens=cfg["max_tokens"],
        stream=True,
    )
    if cfg.get("extra_body"):
        kwargs["extra_body"] = cfg["extra_body"]

    parts = []
    try:
        stream = client.chat.completions.create(**kwargs)
        for chunk in stream:
            if not getattr(chunk, "choices", None):
                continue
            content = getattr(chunk.choices[0].delta, "content", None)
            if content:
                parts.append(content)
    except Exception as e:
        return f"[{cfg['model']} failed: {e}]"
    return "".join(parts).strip()


def _robust_parse(raw: str, expected: type = dict):
    for strategy in [
        lambda s: s,
        lambda s: re.sub(r'^```(?:json)?\s*|\s*```$', '', s).strip(),
        lambda s: re.sub(r',\s*([}\]])', r'\1', s),
    ]:
        try:
            result = json.loads(strategy(raw))
            if isinstance(result, expected):
                return result
        except Exception:
            pass
    for pattern, exp in [(r'\{.*\}', dict), (r'\[.*\]', list)]:
        m = re.search(pattern, raw, re.DOTALL)
        if m:
            try:
                result = json.loads(m.group())
                if isinstance(result, expected):
                    return result
            except Exception:
                pass
    return {} if expected == dict else []


def run_council(agents: list, context: str, final_prompt: str,
                api_key: str, master_key: str = "gpt_120b") -> dict:
    agent_responses = []
    transcript_lines = []

    for agent in agents:
        system = (
            f"You are {agent['name']}, a {agent['role']} on a medical research council.\n\n"
            f"{agent['lens']}\n\n"
            "Be direct, specific, and evidence-based. Give 3-5 key points."
        )
        model_info = COUNCIL_MODELS[agent["model_key"]]
        response   = _call_model(api_key, agent["model_key"], system,
                                 f"Council context:\n\n{context}\n\nGive your expert assessment.")
        agent_responses.append({
            "agent": agent["name"], "role": agent["role"],
            "model": model_info["model"], "response": response,
        })
        transcript_lines.append(
            f"**{agent['name']} ({agent['role']}) [{model_info['model']}]:**\n{response}"
        )

    debate_text = "\n\n---\n\n".join(
        f"{r['agent']} [{r['model']}]:\n{r['response']}" for r in agent_responses
    )
    consensus_context = f"Original context:\n{context}\n\nDebate:\n{debate_text}"

    raw_consensus = _call_model(
        api_key, master_key,
        CONSENSUS_PROMPT + "\n\nReturn ONLY valid JSON.",
        consensus_context,
    )
    consensus = _robust_parse(raw_consensus, dict)
    if not consensus:
        consensus = {"consensus": raw_consensus, "key_points": [], "confidence": "medium"}

    raw_final = _call_model(
        api_key, master_key,
        final_prompt + "\n\nReturn ONLY valid JSON.",
        f"{consensus_context}\n\nCouncil consensus:\n{json.dumps(consensus, indent=2)}",
    )
    final_decision = _robust_parse(raw_final, dict)
    if not final_decision:
        final_decision = {"decision": raw_final}

    return {
        "agents":          agent_responses,
        "consensus":       consensus,
        "final_decision":  final_decision,
        "transcript":      "\n\n".join(transcript_lines),
    }


def council_select_model(params: list, sufficiency: dict, context: dict, client) -> dict:
    api_key = client.api_key
    summary = {
        "total_parameters":   len(params),
        "categories_present": list(set(p.get("category", "") for p in params)),
        "params_with_ci":     sum(1 for p in params if p.get("ci_lower") is not None),
        "derived_params":     sum(1 for p in params if p.get("is_derived")),
        "sufficiency":        sufficiency,
        "sample_params": [
            {k: p.get(k) for k in ["name","category","value","ci_lower","ci_upper","confidence"]}
            for p in params[:8]
        ],
    }
    council_context = (
        f"Research domain: {context.get('domain','Healthcare AI')}\n"
        f"Researcher interest: {context.get('interest','')}\n\n"
        f"Extracted parameters:\n{json.dumps(summary, indent=2)}"
    )
    return run_council(MODEL_SELECTION_AGENTS, council_context, MODEL_COUNCIL_FINAL_PROMPT, api_key)


def council_synthesise_insights(
    sim_results: dict, discovery: dict,
    params: list, gaps: list, context: dict, client,
) -> dict:
    api_key    = client.api_key
    gap_titles = [g.get("title", "") for g in gaps[:5]]
    hypotheses = discovery.get("hypotheses", [])

    council_context = (
        f"Research domain: {context.get('domain','Healthcare AI')}\n\n"
        f"NOVEL HYPOTHESES from cross-paper analysis:\n"
        f"{json.dumps(hypotheses[:3], indent=2)}\n\n"
        f"SIMULATION RESULTS:\n"
        f"Models run: {sim_results.get('models_run', [sim_results.get('model_used','unknown')])}\n"
        f"Headline numbers: {json.dumps(sim_results.get('headline_numbers',{}), indent=2)}\n"
        f"Top sensitivity drivers: {json.dumps(sim_results.get('sensitivity_ranking',[])[:5], indent=2)}\n\n"
        f"RESEARCH GAPS previously identified:\n{json.dumps(gap_titles, indent=2)}\n\n"
        f"Parameters used: {len(params)}"
    )
    return run_council(INSIGHT_SYNTHESIS_AGENTS, council_context, INSIGHT_COUNCIL_FINAL_PROMPT, api_key)
